name: family_expense
description: A daily expense sheet for your family

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

environment:
  sdk: ">=2.12.0 <3.7.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  avatar_glow:
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  # firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^10.4.4
  cloud_firestore: ^4.8.4
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.2.7
  random_string: ^2.3.1
  intl: ^0.18.1
  grouped_list: ^5.1.2
  flutter_slidable: ^3.0.0
  confirm_dialog: ^1.0.2
#  flappy_search_bar: ^1.7.2
  country_codes: ^2.2.0
  flutter_xlider: ^3.5.0
  flutter_chat_bubble: ^2.0.2
  share: ^2.0.4
  random_color: ^1.0.5
  contacts_service: ^0.6.3
  permission_handler: ^10.4.3
  collection: ^1.17.1
  speech_to_text: ^6.3.0
  material_floating_search_bar_2: ^0.5.0
#  barcode_scan: ^0.0.4
#  qr_flutter: ^1.1.1
#  flutter_cupertino_date_picker: ^1.0.26+2


#dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "ui.family" key with the font ui.family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - ui.family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - ui.family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
